### ISSUE TITLE
pymysql.err.ProgrammingError:

### ISSUE THREAD

**Issue by r3xar** [Critical-Start/pastebin_scraper#2]
Hi,
python3 works fine and....
.........
2019-03-19 13:05:29,816 [INFO] [*] Checking https://scrape.pastebin.com/api_scrape_item.php?i=gzzFBnzt
2019-03-19 13:05:30,083 [INFO] [*] FOUND DB_DUMP https://scrape.pastebin.com/api_scrape_item.php?i=gzzFBnzt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/pastebin_scraper/lib/Site.py", line 80, in monitor
    cursor.execute("INSERT INTO pastes (pid, text, emails, hashes, num_emails, num_hashes, type, db_keywords, url, author) VALUES (\""+str(paste.id)+"\",\""+str(paste.text)+"\",\""+str(paste.emails)+"\",\""+str(paste.hashes)+"\",\""+str(paste.num_emails)+"\",\""+str(paste.num_hashes)+"\",\""+str(paste.type)+"\",\""+str(paste.db_keywords)+"\",\""+str(paste.url)+"\",\""+str(paste.author)+"\")")
  File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'Arch Linux"\n2019-03-19 12:33:41 - [sway-1.0/sway/main.c:153] PRETTY_NAME="Arch L\' at line 1')

**Comment by wedemmoez** [comment]
Looks like that [paste ](https://pastebin.com/gzzFBnzt) has  "s scattered through it that break the SQL syntax. I'll add this to my to do list.

**Comment by wedemmoez** [comment]
added a try/except block to catch failures when inserting yo mysql.
