### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by ModernAesthetics** [Critical-Start/pastebin_scraper#3]
2019-03-19 15:33:53,440 [INFO] Monitoring...
2019-03-19 15:33:53,602 [INFO] Retrieving Pastebin ID's
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\PyScripts\pastebin_scraper-master\lib\Site.py", line 68, in monitor
    self.update()
  File "C:\PyScripts\pastebin_scraper-master\lib\Pastebin.py", line 45, in update
    raw_json = json.load(raw)
  File "C:\Python\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wedemmoez** [comment]
It looks like this error is from not having your IP whitelisted in the Pastebin Pro API. [More info here](https://pastebin.com/doc_scraping_api)
