### ISSUE TITLE
Data too long for column 'url' at row 1

### ISSUE THREAD

**Issue by ModernAesthetics** [Critical-Start/pastebin_scraper#4]
2019-03-20 14:47:37,304 [INFO] [*] FOUND DB_DUMP https://scrape.pastebin.com/api_scrape_item.php?i=619Cizjj
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\PyScripts\pastebin_scraper-master\lib\Site.py", line 80, in monitor
    cursor.execute("INSERT INTO pastes (pid, text, emails, hashes, num_emails, num_hashes, type, db_keywords, url, author) VALUES (\""+str(paste.id)+"\",\""+str(paste.text)+"\",\""+str(paste.emails)+"\",\""+str(paste.hashes)+"\",\""+str(paste.num_emails)+"\",\""+str(paste.num_hashes)+"\",\""+str(paste.type)+"\",\""+str(paste.db_keywords)+"\",\""+str(paste.url)+"\",\""+str(paste.author)+"\")")
  File "C:\Python\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'url' at row 1")

**Comment by wedemmoez** [comment]
Quick fix - save the raw paste url instead of the scraping URL (https://pastebin.com/619Cizjj)
Harder fix - , modify your table to have the URL column as a VARCHAR that holds 58 or greater characters.

**Comment by wedemmoez** [comment]
I've pushed a commit for the quick fix, which saves the paste's direct URL instead of the scraping URL.\

https://github.com/Critical-Start/pastebin_scraper/commit/d50803369d4ef29eb162e0139d02e3209ca9b7db

**Comment by wedemmoez** [comment]
Updated the README with an updated SQL command that creates the column as a 60 char instead of 50.
