### ISSUE TITLE
JSON Object Error

### ISSUE THREAD

**Issue by stuttgartPSE** [Critical-Start/pastebin_scraper#7]
It seems that there's an error in your code. I have deployed the original code from your project. But it gives me this error:

    2019-03-25 15:53:24,840 [INFO] Monitoring...
    2019-03-25 15:53:24,849 [INFO] Retrieving Pastebin ID's
    Exception in thread Thread-1:
    Traceback (most recent call last):
    File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
    File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
    File "/opt/pastebin_scraper/lib/Site.py", line 68, in monitor
    self.update()
    File "/opt/pastebin_scraper/lib/Pastebin.py", line 45, in update
    raw_json = json.load(raw)
    File "/usr/lib/python3.5/json/init.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    File "/usr/lib/python3.5/json/init.py", line 312, in loads
    s.class.name))
    TypeError: the JSON object must be str, not 'bytes'

I have the correct IP whitelisted in Pastebin, if I run the the scraping url (**https://scrape.pastebin.com/api_scrape_item.php?i=xx**) by hand, I get results. I use IPv6, and have also whitelisted this IP-address in Pastebin.

**Comment by wedemmoez** [comment]
I haven't been able to duplicate this issue, but i want to help troubleshoot this. Can you provide the output if you replace 
`raw_json = json.load(raw)`
with 
`print(raw)` 
so we can see what the load function is trying to do? I also don't know if IPv6 is causing an issue, I haven't tested that with the script but i shouldn't be causing an issue.

**Comment by wedemmoez** [comment]
Looking at some other stackoverflow answers, it looks like urllib doesn't always play nice with IPv6. You can disable IPv6 on the machine you're using to scrape or use a [workaround](https://stackoverflow.com/questions/18007174/python-urllib2-force-ipv4) to force urllib to use the IPV4 hostname. 

Since the environment that my scraping server is running in doesn't use IPv6, this isn't something I'm going to prioritize fixing or supporting.
